name: "Hello Futurama"

on: [push, pull_request]

jobs:
  hello-futurama:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use the hello-futurama action
      uses: ./
      with:
        character: bender
      id: futurama
    - name: Use the hello-futurama action with invalid character
      uses: ./
      with:
        character: invalid
    - run: echo ${{steps.futurama.outputs.quote}}