name: "Hello Futurama"

on: [push, pull_request]

jobs:
  hello-futurama:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./github/actions
      with:
        character: bender