name: "Repo Dispatch on Version Change"

on:
  push:
    branches: [main]

jobs:
  dispatch-on-version-change:
    name: Send a repository dispatch when the version changes
    runs-on: ubuntu-latest
    steps:
      - uses: ./send-dispatch-on-version-change
        with:
          package-name: "action-demo"
          target-repository: "bleafman/github-actions-playground"
          github-access-token: ${{ secrets.REPO_ACCESS_PAT }}




